# Generated by Django 3.1.4 on 2021-04-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_recyclinginfo_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclinginfo',
            name='impact',
            field=models.IntegerField(default=0),
        ),
    ]
